### ISSUE TITLE
Error Building with 4.0.2

### ISSUE THREAD

**Issue by blindpet** [varnish/libvmod-vsthrottle#6]
I'm on Debian jessie 64-bit and have installed using the Varnish repo, systemd script is working and my vcl works. I previously build vsthrottle with these instructions about a month ago (before the branch renames) but it is no longer working:

```
apt-get install libvarnishapi-dev dpkg-dev pkg-config build-essential git autotools-dev automake libtool -y
```

Then git clone the specific branch for vsthrottle and build it (these instructions work for vshield)

```
cd ~
git clone -b 4.0 https://github.com/varnish/libvmod-vsthrottle
cd libvmod-vsthrottle
sh autogen.sh
./configure --VMODDIR=/usr/lib/varnish/vmods
make
make install
```

This fails, autogen.sh produces this output

```
root@debian:~/libvmod-vsthrottle# ./autogen.sh
+ aclocal -I m4 -I /usr/share/aclocal
+ libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
+ autoheader
+ automake --add-missing --copy --foreign
+ autoconf
```

./configure produces no errors
make produces these errors

```
config.status: executing libtool commands
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/libvmod-vsthrottle/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/root/libvmod-vsthrottle'
Making all in src
make[2]: Entering directory '/root/libvmod-vsthrottle/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/share/varnish/include -I/usr/include/varnish   -g -O2 -MT vmod_vsthrottle.lo -MD -MP -MF .deps/vmod_vsthrottle.Tpo -c -o vmod_vsthrottle.lo vmod_vsthrottle.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/share/varnish/include -I/usr/include/varnish -g -O2 -MT vmod_vsthrottle.lo -MD -MP -MF .deps/vmod_vsthrottle.Tpo -c vmod_vsthrottle.c  -fPIC -DPIC -o .libs/vmod_vsthrottle.o
vmod_vsthrottle.c:113:25: error: expected ')' before 'VCL_STRING'
 vmod_is_denied(VRT_CTX, VCL_STRING key, VCL_INT limit, VCL_DURATION period)
                         ^
Makefile:442: recipe for target 'vmod_vsthrottle.lo' failed
make[2]: *** [vmod_vsthrottle.lo] Error 1
make[2]: Leaving directory '/root/libvmod-vsthrottle/src'
Makefile:482: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/libvmod-vsthrottle'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by daghf** [comment]
Hi.

This is indeed a bug specific to the 4.0 branch (introduced in e662e5e). Should be fixed in branch 4.0 now (42ecef0).

Could I ask you to try again with latest HEAD?

**Comment by blindpet** [comment]
Thank you, confirmed working now. Now to work out what's going on with 4.1
